on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: touch test
            - run: ls
            - run: pwd
            - run: ${{ secrets.Q }}
    job2:
        runs-on: macos-latest
        steps:
            - run: node -v
            - run: npm -v